server:
  port: 8090
  contextPath: /sboot
  servlet-path: /*

spring.datasource:
  driver-class: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/sboot
  username: sboot
  password: sboot

spring.jpa:
  show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.hibernate:
  ddl-auto: create
  naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy


security.basic.enabled: false